# Generated by Django 2.0.3 on 2018-04-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edinet_code', models.CharField(max_length=6)),
                ('company_name', models.CharField(max_length=200)),
                ('english_company_name', models.CharField(max_length=200)),
                ('security_code', models.CharField(max_length=5)),
                ('sector_code', models.CharField(max_length=3)),
                ('stock_market', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edinet_code', models.CharField(max_length=6)),
                ('year', models.CharField(max_length=4)),
                ('type_of_current_period', models.CharField(max_length=2)),
                ('current_fiscal_year_start_date', models.DateField(verbose_name='fiscal year start date')),
                ('current_fiscal_year_end_date', models.DateField(verbose_name='fiscal year end date')),
                ('accounting_standard', models.CharField(max_length=15)),
                ('per', models.DecimalField(decimal_places=3, max_digits=7)),
                ('roe', models.DecimalField(decimal_places=3, max_digits=7)),
                ('eps', models.DecimalField(decimal_places=3, max_digits=7)),
                ('equity_to_asset_ratio', models.DecimalField(decimal_places=3, max_digits=7)),
                ('net_sales', models.IntegerField(default=0)),
                ('net_assets', models.IntegerField(default=0)),
                ('operating_revenue', models.IntegerField(default=0)),
                ('profit_before_tax', models.IntegerField(default=0)),
                ('owners_equity_per_share', models.IntegerField(default=0)),
                ('cash_and_cash_equivalents', models.IntegerField(default=0)),
                ('cash_flow_from_operating', models.IntegerField(default=0)),
                ('cash_flow_from_investing', models.IntegerField(default=0)),
                ('cash_flow_from_financing', models.IntegerField(default=0)),
                ('whether_consolidated_financial_statements', models.BooleanField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('edinet_code', 'year', 'type_of_current_period')},
        ),
    ]
