# Generated by Django 2.0.3 on 2018-04-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20180401_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AlterField(
            model_name='company',
            name='edinet_code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
