# Generated by Django 2.0.3 on 2018-04-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20180401_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ordinary_revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='pay_out_ratio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
    ]
