# Generated by Django 2.0.3 on 2018-04-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20180401_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='eps',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='report',
            name='equity_to_asset_ratio',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='report',
            name='pay_out_ratio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='report',
            name='per',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='report',
            name='roe',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
