# Generated by Django 2.0.3 on 2018-04-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20180401_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_code', models.CharField(default='', max_length=5)),
                ('date', models.DateField(verbose_name='Date of Stock Price')),
                ('stock_price', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('comparison', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('comparison_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('market_capitalization', models.IntegerField(default=0)),
            ],
        ),
    ]
