# Generated by Django 2.0.3 on 2018-04-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_stockprice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together={('security_code', 'date')},
        ),
    ]
