# Generated by Django 2.0.3 on 2018-04-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20180403_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockPrice',
        ),
    ]
