# Generated by Django 2.0.3 on 2018-04-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_delete_stockprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='liabilities',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='total_assets',
            field=models.IntegerField(default=0),
        ),
    ]
